name: docs

on:
  push:
    branches:
      - "galactic"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push docs
        uses: athackst/mkdocs-simple-plugin@v0.8.1
        with:
          publish_branch: gh-pages-galactic
          edit_uri: edit/galactic
