name: ROS

on:
  pull_request:
  push:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Test
        run: |
          docker build -t $GITHUB_REPOSITORY -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE $GITHUB_REPOSITORY \
          bash -c "
          vcs import --skip-existing < src/ros2.repos src \
          && apt-get update \
          && rosdep update \
          && rosdep install --from-paths src --ignore-src -y --rosdistro=foxy \
          && colcon build --cmake-args '-DCMAKE_BUILD_TYPE=Release' -Wall -Wextra -Wpedantic \
          && colcon test \
          "
  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: Run linter
        run: |
          docker build -t $GITHUB_REPOSITORY -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE $GITHUB_REPOSITORY \
          bash -c "
          vcs import --skip-existing < src/ros2.repos src \
          && ament_${{ matrix.linter }} src/
          "
