name: ROS

on:
  pull_request:
  push:
    branches: 
      - humble*
      - iron*
      - rolling*
  workflow_dispatch:
    
jobs:
  test:
    name: test
    runs-on: ubuntu-20.04
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Test
        uses: ./.github/actions/test/

  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v4
      -
        name: Run linter
        uses: ./.github/actions/lint/
        env: 
          LINTER: ${{ matrix.linter }}

  complete:
    name: Tests passed
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: echo "Completed successfully!"
